# Generated by Django 2.0.4 on 2018-04-28 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('contact_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.Tasker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
