# Generated by Django 2.0.4 on 2018-07-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_billing_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
