# Generated by Django 2.0.4 on 2018-05-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180509_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasker',
            old_name='user',
            new_name='tasker',
        ),
    ]
