# Generated by Django 2.0.4 on 2018-05-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180509_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_request',
            name='status',
            field=models.CharField(default='pending', max_length=256, verbose_name='status'),
        ),
    ]
