# Generated by Django 2.0.4 on 2018-05-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180512_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_request',
            name='status',
            field=models.NullBooleanField(default=False),
        ),
    ]
