# Generated by Django 2.0.4 on 2018-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180525_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_request',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('Denied', 'Denied')], default=False, max_length=20),
        ),
    ]
