# Generated by Django 2.0.4 on 2018-05-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180527_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_request',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
