# Generated by Django 2.0.4 on 2018-06-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180606_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='task_request',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Task_Request'),
        ),
    ]
