# Generated by Django 2.0.4 on 2018-06-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180606_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decripe', to='users.Task_Request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='mark_as_read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate', to='users.Task_Request'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='users.Task_Request'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='t', to='users.Task_Request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task_request',
            name='description',
            field=models.CharField(max_length=244),
        ),
    ]
